### ISSUE TITLE
lmao stupid skid

### ISSUE THREAD

**Issue by gov-sec** [Z3NTL3/zib#2]
delete ur skid shit i see stupid nn get off here you edgy 12 year old discord kid

**Comment by Z3NTL3** [comment]
> delete ur skid shit i see stupid nn get off here you edgy 12 year old discord kid

you dont know even what this repistory is lmao, your the biggest skid, you cant even code one line none info

https://lowkeypanel.me 
hate more by watching this baby

**Comment by Z3NTL3** [comment]
*gov sec*

0 followers😂😂😂😂😂

im dying of laughing😂😂😂
